export const mockDefaultGlobalStateTome = {
  characterObject: null,
  deserializedCharacter: null,
  isCharacterGenerated: false,
  isCharacterComplete: false,
  isSavingEnabled: true,
  characterId: null,
  characterName: '',
  player: '',
  race: null,
  class: null,
  gender: null,
  backstory: null,
  attributes: {
    str: 0,
    dex: 0,
    con: 0,
    int: 0,
    wis: 0,
    cha: 0,
  },
  alignment: null,
  alignmentPos: 4,
  weapons: [],
  armor: [],
  skills: [],
  traits: [],
  scrolls: [],
  minions: [],
  xp: 0,
  gold: 0,
  score: 0,
  date: '2020-01-01',
  familiar: null,
  familiarName: null,
  familiarPower: 0,
  fiends: [],
  fiendsBanished: [],
  monster: null,
  monsterLocation: null,
  monsterObstacle: null,
  monsterAttack: null,
  monsterScore: 0,
};

export const mockCompleteGlobalStateTome = {
  characterObject: null,
  deserializedCharacter: null,
  isCharacterGenerated: false,
  isCharacterComplete: false,
  isSavingEnabled: true,
  characterId: 'abc123',
  characterName: 'Test',
  player: 'Tester',
  race: 'abc123',
  class: 'abc123',
  gender: 'male',
  backstory: 'abc123',
  attributes: {
    str: 0,
    dex: 0,
    con: 0,
    int: 0,
    wis: 0,
    cha: 0,
  },
  alignment: 'abc123',
  alignmentPos: 4,
  weapons: ['1', '3', '2'],
  armor: ['2', '3', '1'],
  skills: ['1'],
  traits: [],
  scrolls: ['3', '1'],
  minions: ['3', '1', '4', '2'],
  xp: '1',
  gold: '1',
  score: '1',
  date: '2020-01-01',
  familiar: 'abc123',
  familiarName: null,
  familiarPower: '2',
  fiends: ['2', '1'],
  fiendsBanished: ['2', '3', '1'],
  monster: 'abc123',
  monsterLocation: 'abc123',
  monsterObstacle: 'abc123',
  monsterAttack: 'abc123',
  monsterScore: '1',
};
